package pv207.groceries.com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Products")
   private java.util.List<pv207.groceries.com.Product> products;

   public ProductList()
   {
   }

   public java.util.List<pv207.groceries.com.Product> getProducts()
   {
      return this.products;
   }

   public void setProducts(java.util.List<pv207.groceries.com.Product> products)
   {
      this.products = products;
   }

   public ProductList(java.util.List<pv207.groceries.com.Product> products)
   {
      this.products = products;
   }
   
       @Override
    public String toString() {
        java.lang.String result = "";
        java.lang.Integer numOfItems = 0;
        java.lang.Double finalPrice = 0d;
        for (Product p : products) {
            result+= p.toString();
            result+= "\n";
            numOfItems += p.getQuantity();
            finalPrice = finalPrice + p.getPrice()*p.getQuantity();
        }
        result+= "Number of items: ";
        result = result + numOfItems + "\n";
        result = result + "Order summary: " + finalPrice;
        return result;
    }

}