package pv207.groceries.com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Product name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Product price")
   private java.lang.Double price;
   @org.kie.api.definition.type.Label(value = "Product ID")
   private java.lang.Integer id;

   public Product()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public Product(java.lang.String name, java.lang.Double price,
         java.lang.Integer id)
   {
      this.name = name;
      this.price = price;
      this.id = id;
   }

}