package pv207.groceries.com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StoreOrder implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public StoreOrder() {
    }

}