package pv207.groceries.com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserAccount implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Referrer")
   private java.lang.String referrer;
   @org.kie.api.definition.type.Label(value = "Confirmed")
   private java.lang.Boolean confirmed;

   public UserAccount()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getReferrer()
   {
      return this.referrer;
   }

   public void setReferrer(java.lang.String referrer)
   {
      this.referrer = referrer;
   }

   public java.lang.Boolean getConfirmed()
   {
      return this.confirmed;
   }

   public void setConfirmed(java.lang.Boolean confirmed)
   {
      this.confirmed = confirmed;
   }

   public UserAccount(java.lang.String name, java.lang.String referrer,
         java.lang.Boolean confirmed)
   {
      this.name = name;
      this.referrer = referrer;
      this.confirmed = confirmed;
   }

}